name: Wake Streamlit Apps

on:
  schedule:
    - cron: "0 2 * 3-10 *"
    - cron: "0 3 * 11,12,1,2 *"
  workflow_dispatch:

jobs:
  wake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install playwright
          # On installe le navigateur et ses dépendances système
          python -m playwright install chromium --with-deps

      - name: Run wake script
        run: |
          python wake.py
